# https://github.com/micahhausler/rabbitmq-compose/blob/master/docker-compose.yml
# https://github.com/aznamier/keycloak-event-listener-rabbitmq

name: videoclub
services:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: video-rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "15672:15672"
      - "30567:5672"
    labels:
      NAME: "rabbitmq1"